// Cabides Atelier — Home editorial: descoberta, personalização e carrinho; checkout deliberadamente fora desta rodada.
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Check, Menu, Minus, Plus, Search, ShoppingBag, Sparkles, X } from "lucide-react";
import { Link } from "wouter";
import { categories, formatBRL, products, type Product } from "@/data/catalog";

const STORAGE_KEY = "cabides-atelier-cart";
type CartItem = Omit<Product, "hardware" | "personalization" | "sizes"> & { quantity: number; hardware?: string; personalization?: string; size?: string };
const feeFor = (value?: string) => value === "Laser — frente" ? 2 : value === "Laser — frente e verso" ? 4 : value === "Silk — frente" ? 1.5 : value === "Silk — frente e verso" ? 3 : 0;

function ProductCard({ product, onOpen }: { product: Product; onOpen: (p: Product) => void }) {
  return <article className="product-card">
    <div className="product-image-wrap"><span className="product-index">{product.featured ? "Destaque" : product.category}</span><img src={product.image} alt={`${product.name} — ${product.category}`} loading="lazy" /><button className="quick-view" type="button" onClick={() => onOpen(product)}>Ver detalhes <ArrowRight size={15} /></button></div>
    <div className="product-meta"><p className="eyebrow">{product.category}</p><h3><Link href={`/produto/${product.id}`}>{product.name}</Link></h3><div className="product-bottom"><strong>{formatBRL(product.price)}</strong><span>à vista</span></div><button className="product-detail-link" type="button" onClick={() => onOpen(product)}>Personalizar <ArrowRight size={14} /></button></div>
  </article>;
}

function ProductDrawer({ product, onClose, onAdd }: { product: Product | null; onClose: () => void; onAdd: (item: CartItem) => void }) {
  const [hardware, setHardware] = useState("");
  const [personalization, setPersonalization] = useState("Nenhuma");
  const [size, setSize] = useState("");
  const [quantity, setQuantity] = useState(1);
  useEffect(() => { setHardware(product?.hardware?.[0] || product?.colors?.[0] || ""); setSize(product?.sizes?.[0] || ""); setPersonalization("Nenhuma"); setQuantity(1); }, [product]);
  if (!product) return null;
  const unitPrice = product.price + feeFor(personalization);
  return <div className="drawer-backdrop" role="presentation" onClick={onClose}><aside className="product-drawer" role="dialog" aria-modal="true" aria-label={`Personalizar ${product.name}`} onClick={(e) => e.stopPropagation()}><button className="icon-button drawer-close" type="button" onClick={onClose} aria-label="Fechar detalhes"><X size={20} /></button><div className="drawer-image"><img src={product.image} alt={product.name} /></div><div className="drawer-content"><p className="eyebrow">{product.category}</p><h2>{product.name}</h2><p className="drawer-description">{product.description}</p><div className="drawer-price">{formatBRL(unitPrice)} <small>por unidade</small></div>{(product.hardware || product.colors) && <label className="field-label">{product.hardware ? "Escolha a ferragem" : "Acabamento"}<select value={hardware} onChange={(e) => setHardware(e.target.value)}>{(product.hardware || product.colors || []).map((option) => <option key={option}>{option}</option>)}</select></label>}{product.sizes && <label className="field-label">Tamanho<select value={size} onChange={(e) => setSize(e.target.value)}>{product.sizes.map((option) => <option key={option}>{option}</option>)}</select></label>}{product.personalization && <><label className="field-label">Personalize seu cabide<select value={personalization} onChange={(e) => setPersonalization(e.target.value)}><option>Nenhuma</option><option>Laser — frente</option><option>Laser — frente e verso</option><option>Silk — frente</option><option>Silk — frente e verso</option></select></label><p className="helper-note"><Check size={14} /> A arte final será validada antes da produção.</p></>}<div className="quantity-row"><span>Quantidade</span><div className="quantity-control"><button type="button" onClick={() => setQuantity(Math.max(1, quantity - 1))} aria-label="Diminuir quantidade"><Minus size={15} /></button><strong>{quantity}</strong><button type="button" onClick={() => setQuantity(quantity + 1)} aria-label="Aumentar quantidade"><Plus size={15} /></button></div></div><button className="primary-button full" type="button" onClick={() => { onAdd({ ...product, quantity, hardware, size, personalization }); onClose(); }}>Adicionar ao carrinho <ShoppingBag size={17} /></button><p className="checkout-note">Depois de escolher, fale com o Atelier para confirmar produção, prazo e envio.</p></div></aside></div>;
}

export default function Home() {
  const [activeCategory, setActiveCategory] = useState("Todos");
  const [query, setQuery] = useState("");
  const [sort, setSort] = useState("relevancia");
  const [cart, setCart] = useState<CartItem[]>(() => { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]"); } catch { return []; } });
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [cartOpen, setCartOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => { localStorage.setItem(STORAGE_KEY, JSON.stringify(cart)); }, [cart]);
  useEffect(() => { document.title = "Cabides Atelier — Cabides personalizados"; }, []);
  const filtered = useMemo(() => {
    const term = query.trim().toLowerCase();
    const result = products.filter((p) => (activeCategory === "Todos" || p.category === activeCategory) && `${p.name} ${p.category} ${p.tags.join(" ")}`.toLowerCase().includes(term));
    return [...result].sort((a, b) => sort === "menor-preco" ? a.price - b.price : sort === "maior-preco" ? b.price - a.price : sort === "alfabetica" ? a.name.localeCompare(b.name) : Number(b.featured) - Number(a.featured));
  }, [activeCategory, query, sort]);
  const total = cart.reduce((sum, item) => sum + (item.price + feeFor(item.personalization)) * item.quantity, 0);
  const addToCart = (item: CartItem) => setCart((current) => [...current, item]);
  const removeFromCart = (index: number) => setCart((current) => current.filter((_, i) => i !== index));
  const whatsappText = encodeURIComponent(`Olá! Quero conhecer o Cabides Atelier. ${cart.length ? `Tenho interesse em ${cart.map((i) => `${i.name} (${i.quantity} un.)`).join(", ")}.` : "Gostaria de conhecer o catálogo."}`);
  return <div className="atelier-site"><header className="site-header"><Link href="#inicio" className="brand"><img src="/cabides-atelier-logo.jpg" alt="Cabides Atelier" /><span>Cabides<br /><em>Atelier</em></span></Link><nav className={menuOpen ? "nav open" : "nav"} aria-label="Navegação principal">{[["Catálogo", "catalogo"], ["Personalização", "personalizacao"], ["Atelier", "atelier"], ["Contato", "contato"]].map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav><div className="header-actions"><button className="search-trigger" type="button" onClick={() => document.getElementById("catalog-search")?.focus()} aria-label="Buscar no catálogo"><Search size={18} /></button><button className="bag-button" type="button" onClick={() => setCartOpen(true)} aria-label={`Carrinho com ${cart.length} itens`}><ShoppingBag size={19} /><span>{cart.length}</span></button><button className="menu-button" type="button" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label={menuOpen ? "Fechar menu" : "Abrir menu"}><Menu size={20} /></button></div></header>
    <main><section className="hero" id="inicio"><div className="hero-copy"><p className="eyebrow">ATELIER DE EXPOSIÇÃO · 2026</p><h1>O primeiro olhar começa <em>no detalhe.</em></h1><p className="hero-lede">Cabides personalizados e soluções de exposição para lojas, boutiques e marcas que cuidam da apresentação como parte da experiência.</p><div className="hero-actions"><a className="primary-button" href="#catalogo">Ver catálogo <ArrowRight size={17} /></a><a className="text-button" href="#personalizacao">Personalizar meu cabide <ArrowRight size={16} /></a></div><div className="hero-note"><span>01</span><p>Materiais escolhidos<br />para sua coleção</p></div></div><div className="hero-image"><img src="/products/catalogo-003.jpg" alt="Cabides brancos personalizados em madeira" /><div className="image-caption"><span>PX—01</span><span>Madeira · Metal · Precisão</span></div></div></section>
      <section className="manifesto" id="atelier"><div className="section-index">01 / ATELIER</div><div><p className="eyebrow">Para quem apresenta com intenção</p><h2>O suporte certo muda<br /><em>a leitura da coleção.</em></h2></div><p className="manifesto-text">Do cabide de madeira ao expositor de provador, o Atelier reúne soluções documentadas, combináveis e prontas para acompanhar a rotina de uma marca de moda.</p></section>
      <section className="catalog-section" id="catalogo"><div className="section-heading"><div><p className="eyebrow">02 / CATÁLOGO</p><h2>Escolha por <em>material e função.</em></h2><p className="catalog-result-count">{filtered.length} {filtered.length === 1 ? "produto encontrado" : "produtos encontrados"}</p></div><div className="catalog-controls"><div className="search-box"><Search size={16} /><input id="catalog-search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por nome, material ou uso" aria-label="Buscar no catálogo" /></div><label className="sort-field">Ordenar<select value={sort} onChange={(e) => setSort(e.target.value)} aria-label="Ordenar produtos"><option value="relevancia">Destaques</option><option value="menor-preco">Menor preço</option><option value="maior-preco">Maior preço</option><option value="alfabetica">A–Z</option></select></label></div></div><div className="category-strip" role="tablist" aria-label="Filtrar por categoria">{categories.map((category) => <button key={category} type="button" role="tab" aria-selected={activeCategory === category} className={activeCategory === category ? "active" : ""} onClick={() => setActiveCategory(category)}>{category}</button>)}</div>{(query || activeCategory !== "Todos") && <button className="clear-filters" type="button" onClick={() => { setQuery(""); setActiveCategory("Todos"); setSort("relevancia"); }}>Limpar filtros <X size={13} /></button>}<div className="products-grid">{filtered.map((product) => <ProductCard key={product.id} product={product} onOpen={setSelectedProduct} />)}</div>{filtered.length === 0 && <div className="empty-state"><Sparkles size={22} /><p>Nenhum produto encontrado com este filtro.</p><button className="text-button" type="button" onClick={() => { setQuery(""); setActiveCategory("Todos"); }}>Ver todos os produtos <ArrowRight size={15} /></button></div>}</section>
      <section className="custom-section" id="personalizacao"><div className="custom-image"><img src="/products/catalogo-019.jpg" alt="Cabide para lingerie com acabamento e personalização" /></div><div className="custom-copy"><p className="eyebrow">03 / PERSONALIZAÇÃO</p><h2>Seu nome, sua marca,<br /><em>seu acabamento.</em></h2><p>Escolha entre gravação a laser sem pigmentação ou personalização Silk em uma cor. O adicional é calculado por lado do cabide e a arte final é validada antes da produção.</p><div className="custom-options"><div><strong>01 · Escolha</strong><span>Selecione o modelo, acabamento e ferragem.</span></div><div><strong>02 · Personalize</strong><span>Escolha a técnica e envie sua orientação ao Atelier.</span></div><div><strong>03 · Valide</strong><span>A arte final é confirmada antes da produção.</span></div></div><a className="primary-button" href="#catalogo">Escolher um cabide <ArrowRight size={17} /></a></div></section>
      <section className="service-band" id="contato"><div><p className="eyebrow">04 / ATENDIMENTO</p><h2>Para pedidos especiais,<br /><em>converse com o Atelier.</em></h2></div><div className="service-text"><p>Precisa de volume, uma combinação específica ou ajuda para escolher ferragens? Nossa equipe pode orientar o próximo passo.</p><a className="dark-button" href={`https://wa.me/5500000000000?text=${whatsappText}`} target="_blank" rel="noreferrer">Falar pelo WhatsApp <ArrowRight size={17} /></a><small>Atendimento para dúvidas, combinações e pedidos personalizados.</small></div></section></main>
    <footer className="site-footer"><div className="footer-brand"><img src="/cabides-atelier-logo.jpg" alt="Cabides Atelier" /><div><strong>Cabides Atelier</strong><span>Materiais para apresentar melhor.</span></div></div><div className="footer-links"><a href="#catalogo">Catálogo</a><a href="#personalizacao">Personalização</a><a href="#contato">Contato</a><Link href="/privacidade">Privacidade</Link><Link href="/termos">Termos</Link></div><span className="footer-copy">© 2026 Cabides Atelier</span></footer>
    <ProductDrawer product={selectedProduct} onClose={() => setSelectedProduct(null)} onAdd={addToCart} />{cartOpen && <div className="drawer-backdrop" role="presentation" onClick={() => setCartOpen(false)}><aside className="cart-drawer" role="dialog" aria-modal="true" aria-label="Carrinho" onClick={(e) => e.stopPropagation()}><div className="cart-heading"><div><p className="eyebrow">SEU PEDIDO</p><h2>Carrinho <em>({cart.length})</em></h2></div><button className="icon-button" type="button" onClick={() => setCartOpen(false)} aria-label="Fechar carrinho"><X size={20} /></button></div>{cart.length === 0 ? <div className="empty-cart"><ShoppingBag size={26} /><p>Seu carrinho está pronto para receber uma boa escolha.</p><button className="primary-button" type="button" onClick={() => { setCartOpen(false); document.getElementById("catalogo")?.scrollIntoView(); }}>Explorar catálogo</button></div> : <><div className="cart-items">{cart.map((item, index) => <div className="cart-item" key={`${item.id}-${index}`}><img src={item.image} alt="" /><div><strong>{item.name}</strong><span>{item.quantity} × {formatBRL(item.price + feeFor(item.personalization))}</span>{(item.hardware || item.personalization !== "Nenhuma") && <small>{[item.hardware, item.personalization].filter(Boolean).join(" · ")}</small>}<button type="button" onClick={() => removeFromCart(index)}>Remover</button></div></div>)}</div><div className="cart-summary"><span>Subtotal estimado</span><strong>{formatBRL(total)}</strong></div><a className="primary-button full" href={`https://wa.me/5500000000000?text=${whatsappText}`} target="_blank" rel="noreferrer">Continuar pelo WhatsApp <ArrowRight size={17} /></a><p className="checkout-note">O Atelier confirma produção, prazo e envio antes da finalização.</p></>}</aside></div>}</div>;
}
