// Cabides Atelier — páginas legais informativas; revisar com assessoria jurídica antes de publicação.
import { Link } from "wouter";

type Kind = "privacy" | "terms" | "cookies";
const content: Record<Kind, { eyebrow: string; title: string; intro: string; blocks: [string, string][] }> = {
  privacy: { eyebrow: "Privacidade", title: "Política de privacidade.", intro: "Esta página explica, em linguagem direta, como o Cabides Atelier poderá tratar dados necessários para atendimento, personalização, pedidos e pagamento.", blocks: [["Dados coletados", "Podemos coletar nome, e-mail, telefone, endereço de entrega, dados de personalização e informações técnicas essenciais para funcionamento do site."], ["Finalidades", "Os dados são usados para responder contatos, processar pedidos, acompanhar pagamentos no Asaas, organizar produção e cumprir obrigações legais."], ["Compartilhamento", "Dados necessários ao pagamento podem ser enviados ao Asaas. Não armazenamos dados completos de cartão no site."], ["Direitos", "Você pode solicitar confirmação, acesso, correção, eliminação ou informações sobre o tratamento dos seus dados pelo canal de contato divulgado no site."], ["Atualizações", "O conteúdo poderá ser revisado quando houver mudança relevante no funcionamento do e-commerce ou nas exigências aplicáveis."]] },
  terms: { eyebrow: "Termos de uso", title: "Comprar com clareza.", intro: "Ao navegar ou comprar no Cabides Atelier, você concorda com as condições abaixo, que devem ser complementadas com os dados jurídicos oficiais da empresa antes da publicação.", blocks: [["Catálogo e preços", "Produtos, acabamentos, disponibilidade e preços são apresentados conforme o catálogo mestre fornecido. Medidas, lotes e personalizações podem exigir confirmação comercial."], ["Personalização", "A produção personalizada começa após validação da arte, acabamento e especificações. O cliente é responsável por possuir autorização para usar a marca enviada."], ["Pagamento", "O pagamento será concluído em ambiente Asaas. A confirmação do pedido depende da confirmação financeira recebida pelo sistema."], ["Entrega", "Prazo, frete e condições de entrega devem ser confirmados no pedido conforme localidade, quantidade e disponibilidade de produção."], ["Atendimento", "Dúvidas ou pedidos especiais podem ser encaminhados pelo WhatsApp informado na loja."]] },
  cookies: { eyebrow: "Cookies", title: "Preferências do site.", intro: "Usamos armazenamento local e recursos técnicos mínimos para manter o carrinho, preferências e navegação funcionando.", blocks: [["Essenciais", "Cookies e armazenamento essenciais podem manter itens do carrinho, preferências de consentimento e estabilidade da sessão."], ["Preferências", "O site pode lembrar escolhas feitas em filtros e personalização para tornar a navegação mais prática."], ["Terceiros", "O checkout Asaas e ferramentas futuras de atendimento poderão utilizar seus próprios recursos quando você seguir para esses serviços."], ["Controle", "Você pode limpar o armazenamento do navegador ou alterar as permissões de cookies nas configurações do seu dispositivo."]] },
};

export default function Legal({ kind }: { kind: Kind }) { const page = content[kind]; return <div className="legal-page atelier-legal"><header className="legal-header"><Link href="/" className="legal-brand"><img src="/cabides-atelier-logo.jpg" alt="" /> Cabides <span>Atelier</span></Link><Link href="/" className="legal-back">Voltar para a loja →</Link></header><main className="legal-main"><p className="legal-eyebrow">Cabides Atelier · {page.eyebrow}</p><h1>{page.title}</h1><p className="legal-intro">{page.intro}</p>{page.blocks.map(([title, text]) => <section className="legal-block" key={title}><h2>{title}</h2><p>{text}</p></section>)}</main><footer className="legal-footer">© 2026 Cabides Atelier · Informação institucional</footer></div>; }
